// Import modules
const { Corppass } = require('@govtechsg/singpass-myinfo-oidc-helper');
const fs = require('fs');

/**
 * CorpPass client (Post-NDI)
 *
 * @param {object} config - See https://github.com/GovTechSG/singpass-myinfo-oidc-helper/blob/master/README.md#corppass-post-ndi
 * @returns {Corppass.NdiOidcHelper}
 */
module.exports = (function (config) {
    // There are 2 sets of keys in the JSON file used by MockPass, one used for encrypting, the other for signing,
    // with their algorithms inferred from the `alg` property (ES256 if contains "256", ES512 if contains "512")
    let certPath = process.env.MOCKPASS_ROOT + 'static/certs';
    let keyJson = JSON.parse(fs.readFileSync(`${certPath}/oidc-v2-rp-secret.json`, 'utf8'));

    // See documentation for constructor for NdiOidcHelper class in
    // https://github.com/GovTechSG/singpass-myinfo-oidc-helper/blob/master/src/corppass/corppass-helper-ndi.ts
    let client = new Corppass.NdiOidcHelper(Object.assign(
        {
            // See https://github.com/opengovsg/mockpass/blob/main/README.md#corppass-v2-corppass-oidc
            // on values to use for MockPass
            oidcConfigUrl:
                `${process.env.DEMO_MOCKPASS_BASEURL_INTERNAL}/corppass/v2/.well-known/openid-configuration`,
            clientID: process.env.DEMO_MOCKPASS_CLIENT_ID, // SingPass requires clientID, CorpPass doesn't
            redirectUri: '',
            jweDecryptKey: {
                key: JSON.stringify(keyJson.keys.filter((key) => ('enc' === key.use))[0]), // must be string not object
                format: 'json',
                alg: 'ES256',
            },
            clientAssertionSignKey: {
                key: JSON.stringify(keyJson.keys.filter((key) => ('sig' === key.use))[0]), // must be string not object
                format: 'json',
                alg: 'ES512',
            },
            // Commented out as not used
            // proxyConfig: null,
            // additionalHeaders: null,
            // proxyBaseUrl: '',
        },
        config || {}
    ));

    /**
     * Custom method to replace constructAuthorizationUrl() in creating authorization URL
     *
     * The authorization URL generated by constructAuthorizationUrl() will use the same base URL
     * as oidcConfigUrl in the client config. It is meant to be used client-side in the browser in
     * this application, while oidcConfigUrl is used server-side during the instantiation of the
     * client.
     *
     * This method is needed to replace the base URL of the generated authorization URL in order
     * for it to work in the browser, as it will call the MockPass server externally, which is
     * different from oidcConfigUrl which calls the MockPass server inside the Docker network.
     * E.g. oidcConfigUrl starts with
     * "http://<Docker Compose service name for MockPass server>:<internal port of MockPass server>"
     * while the authorizationUrl should start with "http://localhost:<external port of MockPass server>".
     *
     * @public
     * @param {express.Request} req
     * @returns {Promise<string>}
     */
    client.customCreateAuthUrl = async function (req) {
        // On the `state` & `nonce` method arguments for constructAuthorizationUrl(), they are each
        // "a session-based, unique, and non-guessable value that should be generated per auth session",
        // serving different purposes and are documented in the request params for the authorization endpoint in:
        //   - https://api.singpass.gov.sg/library/login/developers/tutorial1
        //   - https://stg-id.singpass.gov.sg/docs/authorization/api#_authorization_endpoint
        let state = 'corppass-' + req.headers['X-REQUEST-ID']; // header set in src/routes.js, prefix diff from SingPass
        let nonce = req.headers['X-REQUEST-ID']; // use the same value for convenience
        let authUrl = await client.constructAuthorizationUrl(state, nonce);

        return authUrl.replace(process.env.DEMO_MOCKPASS_BASEURL_INTERNAL, process.env.DEMO_MOCKPASS_BASEURL_EXTERNAL);
    };

    return client;
});
