// Import modules
const { MyInfoGovClient } = require('@opengovsg/myinfo-gov-client');
const fs = require('fs');

/**
 * MyInfo Personal client
 *
 * Sample JSON result from MyInfoGovClient.getPerson():
 *     {
 *       "uinFin": "S9812379B",
 *       "data": {
 *         "name": {
 *           "lastupdated": "2020-04-16",
 *           "source": "1",
 *           "classification": "C",
 *           "value": "JOHN DOE"
 *         },
 *         "email": {
 *           "lastupdated": "2020-04-16",
 *           "source": "2",
 *           "classification": "C",
 *           "value": "myinfotesting@gmail.com"
 *         },
 *         "mobileno": {
 *           "lastupdated": "2020-04-16",
 *           "source": "2",
 *           "classification": "C",
 *           "areacode": {
 *             "value": "65"
 *           },
 *           "prefix": {
 *             "value": "+"
 *           },
 *           "nbr": {
 *             "value": "97399245"
 *           }
 *         },
 *         "iat": 1662691469
 *       }
 *     }
 *
 *
 * @param {object} config - See https://github.com/opengovsg/myinfo-gov-client for more info.
 * @returns {MyInfoGovClient}
 */
module.exports = (function (config) {
    let certPath = process.env.MOCKPASS_ROOT + 'static/certs';

    // See https://github.com/opengovsg/myinfo-gov-client/blob/develop/src/MyInfoGovClient.class.ts on params
    // See https://github.com/opengovsg/mockpass/blob/main/README.md#myinfo-v3 and
    // https://github.com/opengovsg/myinfo-gov-client/blob/develop/test/constants.ts on certs to use from MockPass
    let client = new MyInfoGovClient({
        clientId: process.env.DEMO_MOCKPASS_CLIENT_ID,
        clientSecret: process.env.DEMO_MYINFO_CLIENT_SECRET,
        singpassEserviceId: 'singpassEserviceId',
        redirectEndpoint: process.env.DEMO_MYINFO_PERSONAL_ASSERT_ENDPOINT,
        // clientPrivateKey - key.pem's public key, key.pub, is used for serviceProvider.pubKey in
        // https://github.com/opengovsg/mockpass/blob/main/app.js, which in turn is used by verify() in
        // https://github.com/opengovsg/mockpass/blob/main/lib/express/myinfo/controllers.js
        clientPrivateKey: fs.readFileSync(`${certPath}/key.pem`),
        // myInfoPublicKey refers to MOCKPASS_PUBLIC_KEY in
        // https://github.com/opengovsg/mockpass/blob/main/lib/express/myinfo/controllers.js
        myInfoPublicKey: fs.readFileSync(`${certPath}/spcp.crt`),
        // set 'dev' to call dev endpoint (no encryption), 'stg' to call stg endpoint, leave empty for prod
        mode: '', // set to prod so as to test encryption
    });

    // Need to modify the base API URL to point to MockPass cos no way to specify when creating client
    client.baseAPIUrl = process.env.DEMO_MOCKPASS_BASEURL_INTERNAL + '/myinfo/v3'; // use internal cos used server-side

    /**
     * Custom method to replace createRedirectURL() in creating redirect URL
     *
     * The redirect URL generated by createRedirectURL() will use the same base URL
     * as baseAPIUrl in the client config. It is meant to be used client-side in the browser in
     * this application, while baseAPIUrl is used server-side for client.getAccessToken() and
     * client.getPerson().
     *
     * This method is needed to replace the base URL of the generated redirect URL in order
     * for it to work in the browser, as it will call the MockPass server externally, which is
     * different from baseAPIUrl which calls the MockPass server inside the Docker network.
     * E.g. baseAPIUrl starts with
     * "http://<Docker Compose service name for MockPass server>:<internal port of MockPass server>"
     * while the redirectUrl should start with "http://localhost:<external port of MockPass server>".
     *
     * @public
     * @param {express.Request} req
     * @param {MyInfoGovClient.IAuthRequest} authRequest - See IAuthRequest interface in
     *     https://github.com/opengovsg/myinfo-gov-client/blob/develop/src/MyInfoGovClient.class.ts.
     * @returns {string}
     */
    client.customCreateRedirectUrl = function (req, authRequest) {
        let redirectUrl = client.createRedirectURL(authRequest);

        return redirectUrl.replace(
            process.env.DEMO_MOCKPASS_BASEURL_INTERNAL,
            process.env.DEMO_MOCKPASS_BASEURL_EXTERNAL
        );
    };

    return client;
});
